### ISSUE TITLE
Filetypes with same extension not recognized

### ISSUE THREAD

**Issue by PatrickFranken** [minad/mimemagic#17]
Is it somehow possible to handle different filetypes with the same extension but different magic?  
We've this case in our application and we'd like to extend mimemagic to support this.
Before implementing I'd like to know if you already did some investigation or already have some implementation ideas on this?

**Comment by minad** [comment]
No, I haven't done that. Currently I generate the database from the freedesktop database. I don't think that the database supports that directly.

You could check the extension first and check the magic afterwards if there are abiguities. I think this would be a useful addition.

**Comment by PatrickFranken** [comment]
The struggle I've is that currently we're using the extension as key for our extension array. Therefore it is not possible to have two entries by design.
My favorit logic would be
* Look up known filetypes
* If result count > 1 use magic for closer look up
* Return result based on magic

**Comment by minad** [comment]
I suggest three different methods to do the lookup:

1. extension
2. magic
3. extension+magic

extension+magic should not be done transparently since magic needs an opened IO handle.

Just store the entries for the extensions in a list and return the first one for extension and select the right one for extension+magic.

You have to adapt the database generation script and regenerate the database then.

**Comment by PatrickFranken** [comment]
Makes sense! I'll implement it in this way, thanks for the advices. :+1:

**Comment by minad** [comment]
Just for clarification, I mean

~~~ ruby
extensions = {
   'txt' => [first mime, second mime, ...]
}
~~~

looking forward to your patch :)

**Comment by minad** [comment]
Closed since the issue has been stale for years.
