### ISSUE TITLE
Doesn't detect XLSX when generated by OpenOffice/Googledocs

### ISSUE THREAD

**Issue by codingluke** [minad/mimemagic#39]
I just used this gem to detect files by content, and it works perfectly.

The only thing I detected is, that the Overlay features for xlsx, docx is only working for files generated by Microsoft Office. When they are exported by Google Docs or OpenOffice, they are not detected properly.

``` ruby
# Stunden.xlsx is exported from google docs
MimeMagic.by_magic(File.open('Stunden.xlsx'))                                                              
 => #<MimeMagic:0x00000003401ea8 @type="application/zip", @mediatype="application", @subtype="zip"> 

# ex03_Grade Report.xlsx saved by Microsoft Excel 
MimeMagic.by_magic(File.open('ex03_Grade Report.xlsx'))                                                      
 => #<MimeMagic:0x000000033ea230 @type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", @mediatype="application", @subtype="vnd.openxmlformats-officedocument.spreadsheetml.sheet">
```

**Comment by Ranhiru** [comment]
To add to this, files generated by the [RubyXL](https://github.com/weshatheleopard/rubyXL) gem does also seems to be still detected as `application/zip`. 

Please see the attached file.
[hello.xlsx](https://github.com/minad/mimemagic/files/433940/hello.xlsx)

What I am not sure is whether it's matter of you keep updating the overlays to support same file type generated by different tools or the tools generate the correct files to begin with

**Comment by Ranhiru** [comment]
Ultimately what we did was to add another relaxed requirement to MimeMagic

```ruby
x = ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', [[0, "PK\003\004",[[0..5000, 'xl/']]]]]
MimeMagic.add x[0], { magic: x[1] }
```

This would detect files generated using RubyXL correctly.

**Comment by bizangles** [comment]
I've been working on something regarding this issue the past couple days. While these changes would work in a lot of cases, it didn't actually work in the case that I've been trying to fix. In my case, I have a spreadsheet that was modified by RubyXL and the resulting zip file has a .jpg file as the first one. In this case, it takes up way more than the first 3000 characters of the zip and breaks the magic.

Since we're using paperclip which has no option but to use MimeMagic, I have to fix this by manually re-ordering the zip file to have [Content_Types].xml up front, followed by at least on xl/ file. I feel dirty.

**Comment by ypresto** [comment]
If order in zip file is not defined by specification of docx, xlsx or etc, this overlay should not be used anymore.

**Comment by iRet** [comment]
Guys I found an issue in bundled overlay.

When you call it like this `MimeMagic.add(magic[0], magic: magic[1])` i.e. (extensions, parent and comment keys not specified) it overwrites MimeMagic::TYPES value with [], [], nil which is not very good. https://github.com/minad/mimemagic/blob/master/lib/mimemagic.rb#L27-L29

```ruby
[
  [
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    {
      magic: [[0, "PK\003\004", [[0..5000, 'ppt/']]]],
      extensions: %w[pptx],
      parents: %w[application/zip],
      comment: 'PowerPoint 2007 presentation'
    }
  ],
  [
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    { magic: [[0, "PK\003\004", [[0..5000, 'xl/']]]],
      extensions: %w[xlsx],
      parents: %w[application/zip],
      comment: 'Excel 2007 spreadsheet' }
  ],
  [
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    {
      magic: [[0, "PK\003\004", [[0..5000, 'word/']]]],
      extensions: %w[docx],
      parents: %w[application/zip],
      comment: 'Word 2007 document'
    }
  ]
].each do |magic|
  MimeMagic.add(*magic)
end
```

I'm not fully sure if it is safe to match just by PK and word/ it may false trigger on zip containing word folder. It would be better to match by both magic and extension in conjunction.

**Comment by cameronbourgeois** [comment]
Thanks @iRet I was banging my head against the wall on this one.

I am using Rails + Paperclip, and was finding that in my staging environment `MimeMagic.by_magic` was returning correctly in my development environment but not in my staging environment.

Adding an initializer to my Rails app with your code above did the trick.

Cheers!

**Comment by iRet** [comment]
@cameronbourgeois to be honest we've ended with patching paperclip to use file tool first and then mimemagic because method described above does false triggering on zip files which contains word folder inside for example.

Unfortunately there is no way to fix mimemagic of current version to use same logic as file tool since it doesn't support advanced features like relative offsets and so on. See magic file from file tool for more details.
https://github.com/file/file/blob/a25f230f1e7adf1632592d5c81a2d6cc86559c67/magic/Magdir/msooxml

I've been tracing paperclip commits and found that it has started to employ mimemagic to solve docx problems when it wasn't supported by file yet. Then this support has been added and after some time it was broken in mime magic in favour to improve detection.

I'm not sure if I am doing right leaving such comments here but if it will help some one, my temporary fix:
```ruby
# Monkey-patch type_from_file_contents method to use 'file' tool rather
# than mimemagic gem to avoid 3rd party office software docs miss-detection.
# Mimemagic was introduced to support docsx but unfortunately its current
# version does not do it well and IMHO it won't be fixed in future.
# Though, paperclip may get rid of mimemagic completely.
# @see https://ituems.atlassian.net/browse/ETPO-828
module Paperclip
  class ContentTypeDetector
    def type_from_file_contents
      type_from_file_command || type_from_mime_magic
    rescue Errno::ENOENT => e
      Paperclip.log("Error while determining content type: #{e}")
      SENSIBLE_DEFAULT
    end
  end
end

# Above method has been initially taken from Paperclip 5.1.0.
# Please check current implementation and update fix in case it is still actual
# Otherwise remove it.
return if Gem.loaded_specs['paperclip'].version == Gem::Version.new('5.1.0')
warn '[WARNING] Paperclip has been updated. Check initializers/paperclip.rb'

```

**Comment by cameronbourgeois** [comment]
Oh cool @iRet I was also considering the same monkey patch earlier, though I was finding that the file command is returning application/zip on my local machine despite getting the correct mime on my staging server 😆 

I think for now I will stick with the MimeMagic quick fix as seems to be working in both environments. I should be safe from incorrect zip file as my app doesn't accept .zip file extensions and is also not open to general public. I've kept a comment and a link back to this thread with the solution I implemented with your help.

Thanks again - I hope others will also benefit from this thread :)
