### ISSUE TITLE
Word doc detection limited to 5kb

### ISSUE THREAD

**Issue by elliotcm** [minad/mimemagic#80]
Hi there,

Looks like the [overlay setup](https://github.com/minad/mimemagic/blob/master/lib/mimemagic/overlay.rb#L5) only looks in the first 5kb for the signature strings, whereas a sample I have has `[Content_Types].xml` in the 30,000s.

Is there a particular reason for choosing 5000?

**Comment by samwho** [comment]
Adding to this a little.

We also had the problem where the `[Content_Types].xml` file entry was listed near the end of the docx zip file, and we often work with docs in the hundreds of megabytes so it wasn't feasible for us to read all of that in to memory.

We instead created our own overlay that didn't do the check for `[Content_Types].xml`, just the first check for the zip magic number and the check for "word/", "xl/" or "ppt/". However, this doesn't work 100% of the time because the compression inside the zip files can compress these strings away. We're getting around this at the moment by disabling compression in the zip.

It would be nice to have an easy way to scan the last N bytes in the file.

**Comment by IAPark** [comment]
I noticed this fork https://github.com/net-engine/mimemagic/pull/1 that adds support for negative offsets with the behavior of reading the end. Is there a reason this hasn't/can't be up streamed?

**Comment by minad** [comment]
@IAPark Things can surely be upstreamed - as long as the change is "valid". If you look at the issue tracker, there are many issues where people complain about mimemagic being unable to detect certain filetypes and proposing to add some new magic line to the table or modify the existing (auto-generated) table by hand. These proposals are not valid. I won't accept any change, which relies on information, which deviates from the information being present in the freedesktop database. The change in the net-engine fork unfortunately does not seem to fulfill that criterion.

**Comment by IAPark** [comment]
@minad Thanks for getting back. I'm in the process of monkey patching in the net-engine behavior so I just wanted to understand if there was a chance of just merging in the changes. I thought Microsoft Office file types weren't supported by the freedesktop database.

Would it be fair to summarize the objection as being around using negative offsets to read from the end of the file which isn't part of the [freedesktop spec](https://specifications.freedesktop.org/shared-mime-info-spec/shared-mime-info-spec-0.18.html#idm45087060369360)?

Any thoughts on expanding the range MimeMagic searches. Potentially, this could be, accompanied by a change to scan through the range rather than reading it all into ram. Google Docs appears to include enough extra info in even a small doc that when exported it is no longer recognized as a Word Doc by the current logic.


Also not affiliated with net-engine. Just noticed the fork because it was linked from #64 so maybe asking them directly would have been useful

**Comment by minad** [comment]
The objection is that it is not part of the freedesktop spec.

**Comment by minad** [comment]
Invalid, this should be fixed in the shared-mime-info database upstream.

**Comment by elliotcm** [comment]
> Invalid, this should be fixed in the shared-mime-info database upstream.

@minad Can you clarify that this has been fixed upstream already?

**Comment by minad** [comment]
No, I cannot confirm that it has been fixed. But mimemagic only follows upstream. Problems with the mime database should be reported there.

**Comment by elliotcm** [comment]
Well let's hope they don't also wait 15 months before passing the buck.
